# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fclivaz <fclivaz@student.42lausanne.ch>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/04 22:27:45 by fclivaz           #+#    #+#              #
#    Updated: 2025/08/02 14:41:34 by fclivaz          ###   LAUSANNE.ch        #
#                                                                              #
# **************************************************************************** #

services:
  sarif-ng-core:
    container_name: sarif-ng-core
    networks:
      - bw-services
    volumes:
      - sarifng-ssl:/ssl
      - sarifng-data:/data
      - sarifng-libs:/libs
      - sarifng-frontend:/var/www/sarif-frontend
    #ports:
    #- "443:443"
    #- "80:80" can be enabled with USE_TLS=false
    build:
      context: .
    env_file:
      - ../.env
      #- .env
    environment:
      - API_KEY
      - TZ=Europe/Zurich
    depends_on:
      sarif-ng-libs:
        condition: service_completed_successfully
        restart: true
    restart: always
