services:
  usermanager:
    build: ./
    container_name: sarif-ng-usermanager
    environment:
      - TZ=Europe/Zurich
      - API_KEY
    env_file:
      - .env
      - ../.env
    networks:
      - sarifng-net
    volumes:
      - sarif-libs:/libs/
      - sarifng-ssl:/ssl
    depends_on:
      libs:
        condition: service_completed_successfully
        restart: true
      frontend-builder:
        condition: service_completed_successfully
        restart: true
    restart: on-failure
