services:
  blockchain:
    container_name: sarif-ng-blockchain
    networks:
      - sarifng-net
    build:
      context: ./
      args:
        PROVIDER: ${PROVIDER}
        PRIVATE_KEY: ${PRIVATE_KEY}
    env_file:
      - ../.env
      - .env
    environment:
      - API_KEY
    volumes:
      - sarif-libs:/libs/
      - sarifng-ssl:/ssl
    restart: on-failure
    depends_on:
      libs:
        condition: service_completed_successfully
        restart: true
      frontend-builder:
        condition: service_completed_successfully
        restart: true
