services:
  pong:
    container_name: sarif-ng-pong
    networks:
      - sarifng-net
    build: ./
    env_file: ../../.env
    environment:
      - API_KEY
    volumes:
      - sarif-libs:/libs
      - sarifng-ssl:/ssl
    depends_on:
      libs:
        condition: service_completed_successfully
        restart: true
      frontend-builder:
        condition: service_completed_successfully
        restart: true
    restart: on-failure
